Hack systemd to read WSL2_DISTRO_NAME from PID 2
Logs like those should be impossible, but CI showed some:

```
Apr 02 18:22:37 runnervm3zftq wsl-pro-service[178]: DEBUG
github.com/canonical/ubuntu-pro-for-wsl/wsl-pro-service/internal/streams/server.go:146
(*Server).Serve() Server: sent preface messages to all streams
Apr 02 18:22:37 runnervm3zftq wsl-pro-service[178]: DEBUG
D:/a/ubuntu-pro-for-wsl/ubuntu-pro-for-wsl/common/grpc/logconnections/logconnections.go:62
loggedServerStream.RecvMsg() Requesting with parameters: Data:
0x36305e994d50
Apr 02 18:22:37 runnervm3zftq wsl-pro-service[178]: WARNING
github.com/canonical/ubuntu-pro-for-wsl/wsl-pro-service/internal/daemon/daemon.go:194
(*Daemon).serveOnce() Daemon: disconnected from Windows host: serve
error: could not receive ProAttachCmd: rpc error: code = Unknown desc =
WslInstance: could not handle landscape config commands: could not
complete handshake: no WSL name received
Apr 02 18:22:37 runnervm3zftq wsl-pro-service[178]: INFO
github.com/canonical/ubuntu-pro-for-wsl/wsl-pro-service/internal/daemon/daemon.go:144
(*Daemon).Serve.func2() Reconnecting to Windows host in 60 seconds
```

We're modifying logs to allow inspecting the instance name from within wsl-pro-service

Also, we add a check for empty WSL Distro Name.

Finally, because PID 2 is guaranteed to be the forked /init which has the original
environment variables set by the host, while PID 1, the original /init
cleared out its environment just before executing systemd.
Thus if we're running without systemd, we can read WSL_DISTRO_NAME.
If not, maybe we can rely on systemd to tell us the value of
WSL2_DISTRO_NAME from PID 2. :D