Fix unused nolint warning
 Error: wsl-pro-service/cmd/wsl-pro-service/service/export_test.go:13:1: directive `//nolint:revive` is unused for linter "revive" (nolintlint)
  //nolint:revive