Adds a test case to exercise the new assumptions.
Changes in registration key should reconnect.
Changes in log level shouldn't.

Not what we see yet:

```
--- FAIL: TestReconnect (0.00s)
    --- FAIL: TestReconnect/Reconnect_when_changing_the_registration_key (31.62s)
        landscape_test.go:840:
            	Error Trace:	/home/carlos.santanadeoliveira@canonical.com/Dev/1_Work/up4w/windows-agent/internal/proservices/landscape/landscape_test.go:840
            	Error:      	Should be true
            	Test:       	TestReconnect/Reconnect_when_changing_the_registration_key
            	Messages:   	Client should have disconnected
```