Adds a test case to demonstrate the issue
The extra whitespaces would be stripped, causing the raw string comparison to consider that enough to re-run landscape-config,
making the test case fail.

---
=== NAME  TestEnsureValidLandscapeConfig/Do_not_rerun_landscape_due_whitespace_changes
    system_test.go:751:
                Error Trace:    /home/cn/Dev/1_Work/up4w/wsl-pro-service/internal/system/system_test.go:751
                Error:          file "/tmp/TestEnsureValidLandscapeConfigDo_not_rerun_landscape_due_whitespace_changes2859266744/001/.landscape-enabled" exists
                Test:           TestEnsureValidLandscapeConfig/Do_not_rerun_landscape_due_whitespace_changes
                Messages:       Landscape executable should not be ran
--- FAIL: TestEnsureValidLandscapeConfig (0.00s)
    --- PASS: TestEnsureValidLandscapeConfig/Do_not_rerun_landscape_without_modifications (0.98s)
    --- FAIL: TestEnsureValidLandscapeConfig/Do_not_rerun_landscape_due_whitespace_changes (1.85s)
FAIL
FAIL    github.com/canonical/ubuntu-pro-for-wsl/wsl-pro-service/internal/system 1.857s
FAIL