Avoid using the deprecated `/await` msvc flag
Seeing errors in CI like:

C:\Program Files\Microsoft Visual Studio\18\Enterprise\VC\Tools\MSVC\14.51.36231\include\experimental\coroutine(37,1): error C2338: static assertion failed: 'error STL1011: The /await compiler option, <experimental/coroutine>, <experimental/generator>, and <experimental/resumable> are deprecated by Microsoft and will be REMOVED SOON. They are superseded by the C++20 <coroutine> and C++23 <generator> headers. You can define _SILENCE_EXPERIMENTAL_COROUTINE_DEPRECATION_WARNINGS to suppress this error for now.' [D:\a\ubuntu-pro-for-wsl\ubuntu-pro-for-wsl\gui\packages\ubuntupro\build\windows\x64\plugins\p4w_ms_store\p4w_ms_store_plugin.vcxproj]